use_frameworks!

platform :ios, '8.0'

target 'FontWithName_Example' do
  pod 'FontWithName', :path => '../'

  target 'FontWithName_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
